# Generated by Django 5.0.7 on 2024-08-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='duedate',
            new_name='due_date',
        ),
    ]
